name: "pre-release"

on:
  push:
    branches:
      - "develop"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Run tests"
        run: ./gradlew check

      - name: "Build distributable tar"
        run: ./gradlew distTar

      - name: "Move tar to top level dir"
        run: mv self-server/build/distributions/*.tar ./self-server.tar

      - name: "Make pre-release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            self-server.tar