name: "Release: Docker Publish"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release: Docker Publish"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Run tests"
        run: ./gradlew check

      - name: "Build distributable tar"
        run: ./gradlew distTar

      - name: "Cd into docker directory and untar dist"
        run: |
          cd scripts
          tar -xf ../self-server/build/distributions/self-server-*.tar -C ./ --strip-components=1

      - name: "Build and release docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./scripts
          tags: chrisbattarbee/self-server:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"