name: "Release: Docker Publish"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release: Docker Publish"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Run tests"
        run: ./gradlew check

      - name: "Compile conjure definitions"
        run: ./gradlew compileConjure

      - name: "Build all projects"
        run: ./gradlew build

      - name: "Build self magritte"
        run: ./gradlew self_magritte_build

      - name: "Build distributable tar"
        run: ./gradlew distTar

      - name: "Log in to docker hub."
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build self server docker image and push to docker hub"
        run: ./scripts/self-server/build_docker.sh

      - name: "Build self magritte docker image and push to docker hub"
        run: ./scripts/self-magritte/build_docker.sh