name: "Release: Docker Publish"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release: Docker Publish"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Run tests"
        run: ./gradlew check

      - name: "Build distributable tar"
        run: ./gradlew distTar

      - name: "Log in to docker hub."
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build docker image and push to docker hub"
        run: ./scripts/build_docker.sh